name: Cron auto-release
on:
  schedule:
    - cron: "0 4 * * *"
permissions:
  contents: write
  packages: write
jobs:
  call-increment-tag-version:
    uses: ./.github/workflows/increment-tag-version.yaml
    secrets:
      slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN_GITHUB_ACTIONS }}
  call-test:
    if: ${{ needs.call-increment-tag-version.outputs.latest_tag_sha && (github.sha != needs.call-increment-tag-version.outputs.latest_tag_sha) }}
    needs: [ call-increment-tag-version ]
    uses: ./.github/workflows/test.yaml
    secrets:
      username: ${{ secrets.IMAGE_GITHUB_USERNAME }}
      password: ${{ secrets.IMAGE_GITHUB_PASSWORD }}
      slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN_GITHUB_ACTIONS }}
  call-publish:
    needs: [ call-increment-tag-version, call-test ]
    uses: ./.github/workflows/publish.yaml
    secrets:
      username: ${{ secrets.IMAGE_GITHUB_USERNAME }}
      password: ${{ secrets.IMAGE_GITHUB_PASSWORD }}
      slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN_GITHUB_ACTIONS }}
    with:
      app_version: ${{ needs.call-increment-tag-version.outputs.new_tag_name }}
  create-release:
    needs: [ call-increment-tag-version, call-publish ]
    uses: ./.github/workflows/create-release.yaml
    secrets:
      slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN_GITHUB_ACTIONS }}
    with:
      tag_name: ${{ needs.call-increment-tag-version.outputs.new_tag_name }}
      target_commit_hash: ${{ github.sha }}
