name: Cron auto-release
on:
  schedule:
    - cron: "0 4 * * *"
permissions:
  contents: write
  packages: write
jobs:
  call-increment-tag-version:
    uses: ./.github/workflows/increment-tag-version.yaml
  call-test:
    if: ${{ (needs.call-increment-tag-version.outputs.latest_tag_sha != '') && (github.sha != needs.call-increment-tag-version.outputs.latest_tag_sha) }}
    needs: [ call-increment-tag-version ]
    uses: ./.github/workflows/test.yaml
    secrets:
      username: ${{ secrets.IMAGE_GITHUB_USERNAME }}
      password: ${{ secrets.IMAGE_GITHUB_PASSWORD }}
  call-publish:
    needs: [ verify, call-test ]
    uses: ./.github/workflows/publish.yaml
    secrets:
      username: ${{ secrets.IMAGE_GITHUB_USERNAME }}
      password: ${{ secrets.IMAGE_GITHUB_PASSWORD }}
    with:
      app_version: ${{ needs.verify.outputs.new_tag_name }}
  create-release:
    needs: [ verify, call-publish ]
    runs-on: ubuntu-20.04
    steps:
    - name: Create github release
      uses: softprops/action-gh-release@v1
      with:
        name: Autogenerated release
        tag_name: ${{ needs.verify.outputs.new_tag_name }}
        target_commitish: ${{ github.sha }}
        generate_release_notes: true
