name: Scan
on:
  workflow_call:
    inputs:
      tag_name:
        type: string
        required: true
        description: The tag name used for the GitHub release.
      target_commit_hash:
        type: string
        required: true
        description: The commit hash on which the GitHub release is performed.
      disable_slack:
        type: boolean
        default: false
        required: false
        description: Whether to send slack message describing this workflow's status or not.
    secrets:
      slack_bot_token:
        description: The slack bot token used to send slack messages describing this workflow's states.
        required: false
jobs:
  create-release:
    name: Get latest tag
    runs-on: ubuntu-20.04
    steps:
      - name: Create github release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ input.tag_name }}
          target_commitish: ${{ input.target_commit_hash }}
          generate_release_notes: true
      - name: Slack Notification
        uses: slackapi/slack-github-action@v1.19.0
        if: ${{ ! inputs.disable_slack }} && ${{ failure() }}
        with:
          channel-id: "C03PH5M17KR"
          slack-message: "${{ github.workflow }}\nFAILED: ${{ github.job }}\nSee: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack_bot_token }}
