name: Hello
on:
  push: {}
jobs:
  first-job:
    name: First Job
    runs-on: ubuntu-20.04
    steps:
      - name: Hello
        run: echo Hello
      - name: World
        run: echo World
  second-job:
    name: First Job
    runs-on: ubuntu-20.04
    needs:
      - first-job
    steps:
      - name: Foo
        run: echo Foo
      - name: Bar
        run: echo Bar
  catch-job:
    name: First Job
    runs-on: ubuntu-20.04
    if: ${{ failure() }}
    steps:
      - name: Done
        run: echo Done
