name: Hello
on:
  push: {}
jobs:
  call-test:
    runs-on: ubuntu-20.04
    steps:
      - run: echo test
      - run: exit 1
      - name: Slack Notification
        uses: slackapi/slack-github-action@v1.19.0
        if: ${{ failure() }}
        with:
          channel-id: "C03PH5M17KR"
          slack-message: "Failed test: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN_GITHUB_ACTIONS }}
  call-merge-pr:
    runs-on: ubuntu-20.04
    needs: [ call-test ]
    steps:
      - run: echo call-merge-pr
      - name: Slack Notification
        uses: slackapi/slack-github-action@v1.19.0
        if: ${{ failure() }}
        with:
          channel-id: "C03PH5M17KR"
          slack-message: "Failed merging PR: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN_GITHUB_ACTIONS }}
