name: Hello
on:
  push: {}
jobs:
  first-job:
    name: First Job
    runs-on: ubuntu-20.04
    steps:
      - name: Hello
        run: echo Hello
      - name: World
        run: echo World
  second-job:
    name: First Job
    runs-on: ubuntu-20.04
    steps:
      - name: Foo
        run: echo Foo
      - name: Bar
        run: echo Bar
