name: Hello
on:
  push: {}
jobs:
  call-test:
    runs-on: ubuntu-20.04
    steps:
      - run: exit 1
      - run: echo test
      - name: Slack Notification
        uses: slackapi/slack-github-action@v1.19.0
        if: ${{ failure() }}
        with:
          channel-id: "C03PH5M17KR"
          slack-message: "Failed ${{ github.job }}\nSee: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN_GITHUB_ACTIONS }}
  call-merge-pr:
    runs-on: ubuntu-20.04
    needs: [ call-test ]
    steps:
      - run: echo call-merge-pr
      - name: Slack Notification
        uses: slackapi/slack-github-action@v1.19.0
        if: ${{ failure() }}
        with:
          channel-id: "C03PH5M17KR"
          slack-message: "Failed ${{ github.job }}\nSee: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN_GITHUB_ACTIONS }}
