name: Hello
on:
  push: {}
jobs:
  get-latest-tag:
    uses: ./.github/workflows/test.yaml
    secrets:
      username: ${{ secrets.IMAGE_GITHUB_USERNAME }}
      password: ${{ secrets.IMAGE_GITHUB_PASSWORD }}
      slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN_GITHUB_ACTIONS }}
  scan:
    name: Scan
    runs-on: ubuntu-20.04
    needs: [ get-latest-tag ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Run image scan
        run: exit 1
