name: Merge dependabot pr
on:
  workflow_call:
    secrets:
      ext_github_token:
        required: true
        description: The github token used to merge the pr.
permissions:
  pull-requests: write
  contents: write
jobs:
  merge-pr:
    runs-on: ubuntu-20.04
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.ext_github_token }}
