name: Publish
on:
  workflow_call:
    inputs:
      app_version:
        required: true
        type: string
        description: The app version to be published.
      enable_docker_cache:
        required: false
        description: Whether to enable the docker cache or not.
        type: boolean
        default: false
      enable_qemu:
        required: false
        description: Whether to enable the static qemu binaries or not (required for docker multiplatform building).
        type: boolean
        default: false
      disable_slack:
        type: boolean
        default: false
        required: false
        description: Whether to send slack message describing this workflow's status or not.
    secrets:
      username:
        required: true
        description: The github username.
      password:
        required: true
        description: The github password/token.
      slack_bot_token:
        description: The slack bot token used to send slack messages describing this workflow's states.
        required: false
permissions:
  contents: read
  packages: write
jobs:
  publish:
    name: Publishing
    runs-on: ubuntu-20.04
    steps:
      - name: Set up QEMU
        if: ${{ inputs.enable_qemu }}
        uses: docker/setup-qemu-action@v2
      - name: Enable docker cache
        if: ${{ inputs.enable_docker_cache }}
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          key: ${{ github.repository }}-docker-cache-{hash}
          restore-keys: |
            ${{ github.repository }}-docker-cache-
      - name: Login into docker
        uses: azure/docker-login@v1
        with:
          login-server: ghcr.io
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Build and publish
        env:
          VERSION_APP: ${{ inputs.app_version }}
          GITHUB_TOKEN: ${{ secrets.password }}
          DOCKER_USERNAME: ${{ secrets.username }}
          DOCKER_PASSWORD: ${{ secrets.password }}
          IMAGE_BUILDER_CMD_EXTRA_ARGS: --no-cache
        run: make publish
      - name: Slack Notification
        uses: slackapi/slack-github-action@v1.19.0
        if: ${{ ! inputs.disable_slack }} && ${{ failure() }}
        with:
          channel-id: "C03PH5M17KR"
          slack-message: "${{ github.workflow }}\nFAILED: ${{ github.job }}\nSee: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack_bot_token }}
