name: Scan
on:
  workflow_call:
    inputs:
      disable_docker_cache:
        required: false
        description: Whether to disable the docker cache or not.
        type: boolean
        default: false
    secrets:
      username:
        required: true
        description: The github username.
      password:
        required: true
        description: The github password/token.
jobs:
  get-latest-tag:
    name: Get latest tag
    runs-on: ubuntu-20.04
    outputs:
      latest_tag: ${{ steps.get_latest_tag.outputs.latest_tag }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Get latest tag
        id: get_latest_tag
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "::set-output name=latest_tag::$(gh release list -L 1 | cut -f3)"
  scan:
    name: Scan
    runs-on: ubuntu-20.04
    needs: [ get-latest-tag ]
    if: ${{ needs.get-latest-tag.outputs.latest_tag }}
    steps:
      - name: Enable docker cache
        if: ${{ !inputs.disable_docker_cache }}
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          key: ${{ github.repository }}-docker-cache-{hash}
          restore-keys: |
            ${{ github.repository }}-docker-cache-
      - name: Login into docker
        uses: azure/docker-login@v1
        with:
          login-server: ghcr.io
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run image scan
        env:
          GITHUB_TOKEN: ${{ secrets.password }}
          DOCKER_USERNAME: ${{ secrets.username }}
          DOCKER_PASSWORD: ${{ secrets.password }}
          VERSION_APP: ${{ needs.get-latest-tag.outputs.latest_tag }}
        run: make scan
