name: Scan
on:
  workflow_call:
    secrets:
      username:
        required: true
        description: The github username.
      password:
        required: true
        description: The github password/token.
jobs:
  scan:
    name: Scan
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Enable docker cache
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          key: ${{ github.repository }}-docker-cache-{hash}
          restore-keys: |
            ${{ github.repository }}-docker-cache-
      - name: Login into docker
        uses: azure/docker-login@v1
        with:
          login-server: ghcr.io
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
      - name: Run image scan
        env:
          GITHUB_TOKEN: ${{ secrets.password }}
          DOCKER_USERNAME: ${{ secrets.username }}
          DOCKER_PASSWORD: ${{ secrets.password }}
        run: make scan VERSION_APP="$(gh release list -L 1 | cut -f3)"
